extends Node


var PLAYER_SPEED: float = 5.0
var PLAYER_SPRINT_SPEED: float = 8.0
var PLAYER_JUMP_VELOCITY: float = 4.5
var PLAYER_CROUCH_SPEED: float = 3.0
var PLAYER_ACCELERATION: float = 0.1
var PLAYER_DECELERATION: float = 0.25
var MAX_PLAYER_WALKING_ANIM_SPEED: float = 2.2
var MAX_PLAYER_SPRINTING_ANIM_SPEED: float = 2.2
